### ISSUE TITLE
Promises not resolving when in a Periodic Timer

### ISSUE THREAD

**Issue by adamlc** [WyriHaximus/react-guzzle-psr7#1]
Hi, I'm not sure if its possible but I'm trying to poll an API every x seconds. But when I try the following for example the promises never get resolved. Am I doing something wrong?

``` php
<?php
require dirname(__DIR__) . '/vendor/autoload.php';

use GuzzleHttp\Client;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Psr7\Response;
use React\EventLoop\Factory;
use WyriHaximus\React\GuzzlePsr7\HttpClientAdapter;

$loop = Factory::create();

$client = new Client([
    'handler' => HandlerStack::create(new HttpClientAdapter($loop)),
]);

$loop->addPeriodicTimer(5, function() use (&$client) {
    echo 'Loading content', PHP_EOL;

    $promise = $client->getAsync('http://blog.wyrihaximus.net/');
    $promise->then(function(Response $response) { // Success callback
        var_dump($response);
        echo 'Content loaded', PHP_EOL;
    });
});


$loop->run();
```

My actual use case is within the Amazon EC2 SDK to check if an instance has booted or not.

**Comment by WyriHaximus** [comment]
Odd, can you test something for me? What is the outcome of this:

``` php
    $promise->then(function(Response $response) { // Success callback
        var_dump($response);
        echo 'Content loaded', PHP_EOL;
    }, function ($error) {
        echo $error->getMessage(), PHP_EOL; // If this just gives some underlying stream error, keep appending ->getMessage() to ->getMessage()
        var_export($error);
    });
```

**Comment by adamlc** [comment]
Nothing at all really, just get this:

``` bash
Adams-MacBook-Pro:examples mooloop$ php basic_error.php
Loading content
Loading content
Loading content
^C
```

The event loop is LibEventLoop. Not sure if its something specific to that? PHP version info (running on OSX):

``` bash
PHP 5.6.9 (cli) (built: May 15 2015 09:36:14)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.3.2, Copyright (c) 2002-2015, by Derick Rethans
```

``` bash
Adams-MacBook-Pro:examples mooloop$ brew list | grep php56
php56
php56-amqp
php56-intl
php56-libevent
php56-mcrypt
php56-mongo
php56-pcntl
php56-xdebug
```

Hope that helps. I have tried putting a ->wait(false) on the promises, but that just seems to show a "Only one event_base_loop can run on each event_base at once" error

**Comment by WyriHaximus** [comment]
I'll push my current local working version tonight or during the weekend. Refactoring a lot in the way things work so it might be that there is a mismatch somewhere that's causing issues for you. I'll comment here again once they're up :).

**Comment by adamlc** [comment]
Awesome thanks!

**Comment by WyriHaximus** [comment]
Yeah pushing that completely broke it. Going to fix it and get back to you :).

**Comment by WyriHaximus** [comment]
Found it and fixed out. For some reason during a timer the task queue Guzzle uses internally doesn't run when the request are done within a timer. Don't ask me why I'm still trying to figure that out :).

**Comment by adamlc** [comment]
Awesome! I'll give it a test :)

**Comment by WyriHaximus** [comment]
Great, please let me know how it work out :)
