### ISSUE TITLE
using a proxy

### ISSUE THREAD

**Issue by rezaxdi** [WyriHaximus/react-guzzle-psr7#11]
Hi

Is this package compatible with guzzle proxy option ? Because whatever I set inside proxy option of guzzle asyncGet it just seems to be skipped.

**Comment by WyriHaximus** [comment]
It will be soon, currently working on a [PR](https://github.com/WyriHaximus/react-guzzle-http-client/pull/6) on the worker package that will indirectly add [proxy support](https://github.com/clue/php-buzz-react#socks-proxy).

**Comment by WyriHaximus** [comment]
Added a [proxy example](https://github.com/WyriHaximus/react-guzzle-psr7/blob/master/examples/basic-proxy.php), once https://github.com/WyriHaximus/react-guzzle-http-client/pull/6 is merged and tagged it will work, for SOCKS proxies only for now :). I'll keep you posted.
