### ISSUE TITLE
react/promise

### ISSUE THREAD

**Issue by sm2017** [WyriHaximus/react-guzzle-psr7#16]
In your `ReactPHP HttpClient Adapter` , any Async method returns `\GuzzleHttp\Promise\Promise` 

How can I force Async methods return `\React\Promise` , I want to use `done()` function to force thrown uncaught exception for rejected promise

**Comment by WyriHaximus** [comment]
Take a look at https://github.com/reactphp/promise/pull/68 @jsor added support for foreign `done` methods in that PR.
