### ISSUE TITLE
Not working with Transfer-Encoding: chunked

### ISSUE THREAD

**Issue by cyingfan** [WyriHaximus/react-guzzle-psr7#17]
Slightly changing the example in README.MD to show the errors

``` php
$loop = \React\EventLoop\Factory::create();
$handler = new \WyriHaximus\React\GuzzlePsr7\HttpClientAdapter($loop);
$client = new \GuzzleHttp\Client([
    'handler' => \GuzzleHttp\HandlerStack::create($handler),
]);
$client->getAsync('http://php.net/')->then(function ($response) {
    var_export($response->getStatusCode());
    var_export($response->getBody());
}, function($e) {
    var_dump($e->getMessage(), $e->getPrevious()->getMessage(), $e->getPrevious()->getPrevious()->getMessage(), $e->getPrevious()->getPrevious()->getTraceAsString());
});
$loop->run();
```

yields

> string(32) "An error occured in the response"
> string(42) "An error occurred in the underlying stream"
> string(4129) "Unable to validate "en/language.constants.php'>Constants</a></dd>
>        <dd><a href='/manual/en/language.expressions.php'>Expressions</a></dd>
>        <dd><a href='/manual/en/language.operators.php'>Operators</a></dd>
>        <dd><a href='/manual/en/language.control-structures.php'>Control Structures</a></dd>
>        <dd><a href='/manual/en/language.functions.php'>Functions</a></dd>
>        <dd><a href='/manual/en/language.oop5.php'>Classes and Objects</a></dd>
>        <dd><a href='/manual/en/language.namespaces.php'>Namespaces</a></dd>
>        <dd><a h"...
> string(1114) "#0 /var/www/quadra/healthengine.com.au/lib/vendor/react/http->client/src/ChunkedStreamDecoder.php(70): React\HttpClient\ChunkedStreamDecoder->iterateBuffer()
> # 1 [internal function]: React\HttpClient\ChunkedStreamDecoder->handleData('en/language.con...', >Object(React\Stream\Stream))
> # 2 >/var/www/quadra/healthengine.com.au/lib/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(64): call_user_func_array(Array, Array)
> # 3 /var/www/quadra/healthengine.com.au/lib/vendor/react/stream/src/Stream.php(153): "...

**Comment by WyriHaximus** [comment]
Please see https://github.com/reactphp/http-client/pull/68 we're aware and fixing it. Thanks for reporting non the less :+1:
