### ISSUE TITLE
Possible incompatibility issue

### ISSUE THREAD

**Issue by Akhawais** [WyriHaximus/react-guzzle-psr7#18]
I'm using the [ratchephpt/Pawl](/ratchetphp/Pawl) WS client on the same loop as the one I've set for this Guzzle handler.

Async requests are generally fine but sync. requests either run instantly and work fine or they hang for a long while and then cause the WebSocket connection to die (Sending or Receiving messages fail without any exceptions).

Using the default Guzzle handler along with Pawl works fine, but I do need async requests so am a bit stuck here.

(Also would it be better if I posted this in `reactphp/http-client` since it uses that?)

**Comment by WyriHaximus** [comment]
First things first, when you're in a shared running event loop with other tools like Pawl using that event loop never ever make sync requests but always make them async. The reason behind that is that sync requests will block until they're done. If you don't have a really hard dependency on Guzzle. Take a look at https://github.com/clue/php-buzz-react it's a full PSR-7 async first client. I've recently swapped out Guzzle for that client for @php-api-clients purely for the ease of streaming in response.

**Comment by WyriHaximus** [comment]
P.S. Don't get me wrong, Guzzle is a great tool, but it uses certain tricks to bridge sync and async. Tricks you're most likely running into now. For my users that start out those aren't a direct issue they even bump into and gives them a great start doing async stuff in PHP 😄 .

**Comment by Akhawais** [comment]
Thanks for your quick response. I do have a hard dependency on Guzzle, but thanks for telling me about Buzz.

I'll be moving all sync requests over to async. Would you recommend using the `$promise->wait();` when I need the request to finish, using the shared loop, or not?

**Comment by WyriHaximus** [comment]
No problem. Take a look at Buzz and see if the change is worth it for you.

No as that will block everything. Instead do something like this:

``` php
$promise->then(function ($result) {
    // Handle result here
});
```

If you do like the sync flow of calling things take a look at https://github.com/recoilphp/recoil

**Comment by Akhawais** [comment]
Will do, thanks!

Ah okay, I am using that syntax already but yeah I guess using `->wait();` takes me back to square 1 😄 

Thanks very much for your help!

**Comment by WyriHaximus** [comment]
No problem, glad to help out :+1: .
