### ISSUE TITLE
Please use tags

### ISSUE THREAD

**Issue by brstgt** [WyriHaximus/react-guzzle-psr7#21]
1. Thanks a lot for all the effort you put into that very helpful module!
2. Could you please tag stable releases so users are able to pull in a versioned requirement.

If you cannot version the requirements it is very difficult to maintain a consistent and reproducible dependency structure.

Thanks a lot!

**Comment by WyriHaximus** [comment]
> Thanks a lot for all the effort you put into that very helpful module!

Thank you, glad to hear it!

> Could you please tag stable releases so users are able to pull in a versioned requirement.

FYI this package does have stable tags: https://github.com/WyriHaximus/react-guzzle-psr7/releases

**Comment by brstgt** [comment]
You are right :) 2.0.0 should do it. Thanks!

**Comment by WyriHaximus** [comment]
:+1:
