### ISSUE TITLE
What's the difference / which is better?

### ISSUE THREAD

**Issue by garrettw** [WyriHaximus/react-guzzle-psr7#23]
I'm in the process of rewriting a library that depends on this repo.
Today I came across [this article](http://stephencoakley.com/2015/06/11/integrating-guzzle-6-asynchronous-requests-with-reactphp) which precisely details one way to make guzzle and react play nicely together – however I noticed some differences between your code and his.

Did you base the current structure of your lib on the code in that article? If so, I would assume any differences must be due to your vision for improving on the article's code.
If your lib is better, can you point out why?

**Comment by WyriHaximus** [comment]
It depends on bit what your goal is and requirements are. The aim for this package always has been to provide a bridge between sync and async userland. It isn't perfect but fits the needs of the 80% looking for such a bridge. If you want to go for a full PSR-7 async HTTP client take a look at https://github.com/clue/php-buzz-react (and make sure to read [the bit about streaming](https://github.com/clue/php-buzz-react#streaming)), assuming you don't have a hard dependency on Guzzle. This package uses that client under the hood. However if you do have a hard requirement on Guzzle I would love to head if you ran in any sorts of issues that could use addressing. Also this package wasn't based on that article, but there are somethings in it that could be interesting to try out :+1: .

**Comment by garrettw** [comment]
I did look at Buzz. As far as I can tell, Guzzle seems to be reasonably good at async stuff -- with the exception that it's just not built on React.
If this package is merely meant to bridge React and Guzzle, why would it use Buzz at all?
Also, I notice that this package directly uses React's HTTP client -- my question is the same about that if Guzzle is already around. I don't get it.

(I don't have a hard dep on Guzzle in the sense that I'm open to changing it at this stage of the rewrite. However, Guzzle seems so full-featured that I'm thinking about sticking with it.)

Two differences I notice between your code and the article:
- The article uses Guzzle's CurlMultiHandler, whereas your adapter *is* a handler. Is that just to avoid depending on curl?
- The article uses `$loop->addPeriodicTimer()` once, whereas you call `$loop->addTimer()` after every promise returns. I don't know if one way is better than the other.

**Comment by WyriHaximus** [comment]
What is your goal here? Do you want to integrate it in a full async project with event loop and all or do you want to make a group of requests async on a specific point in your project?

This package uses Buzz (through an intermediary package), which uses React's `http-client`, to bring as much features as possible, such as proxies, to the Guzzle adapter/handler. Thus creating a bridge between those two. Haven't looked at Guzzle's in ages so I'll look into the promise resolving after the weekend (have something today), to see how and where it can be improved.

As far as the dependency on Curl goes, it's build into PHP so that doesn't really matter. The reason for using react instead of curl is so it works in full async/non-blocking apps that do more then just a bunch of async HTTP requests.

**Comment by garrettw** [comment]
My project is full async. It's a Discord bot library (their API requires both a WebSockets client as well as an HTTP client). I gather that you would steer me toward Buzz for this.

**Comment by WyriHaximus** [comment]
Ow cool! Been looking into a bit for that myself tbh. But anyway if you're looking for a WebSockets client take a look at [`Pawl`](https://github.com/ratchetphp/Pawl) or [`RxWebsocket`](https://github.com/rxphp/rxwebsocket), been using the latter in [`api-clients/pusher`](https://github.com/php-api-clients/pusher) with great success and joy. (Although [`RxPHP`](https://github.com/ReactiveX/RxPHP) has a bit of a learning curve, it's pretty awesome once you get the hang of it.) This all does steers you more torwards Buzz than than Guzzle. Initially started working on [`php-api-clients`](https://github.com/php-api-clients) with Guzzle as transport (HTTP client) but for various reasons I've ended up suing Buzz instead and even [infused it with middleware[(https://github.com/php-api-clients/transport#middleware) (not the upcoming PSR-15 middleware). But it all depends on your projects needs in the end

**Comment by garrettw** [comment]
I think I'll go with Buzz then.
I was already looking at Pawl as I hadn't come across anything else that was maintained. Thanks for making me aware of RxWebSocket and RxPHP. Now I'll just have to decide which client I like better.

Interestingly enough, I notice that Pawl's composer.json suggests installing RxPHP. Now I feel compelled to figure out how it uses it.

**Comment by WyriHaximus** [comment]
Cheers, let me know if you need any help with any of those. Alternatively you can find the RxPHP guys and the maintainer of bluzz on IRC in the @reactphp channel. Channel is on the topof our website: https://reactphp.org/
