### ISSUE TITLE
ReactPHP HTTPClient Factory not found

### ISSUE THREAD

**Issue by ryan-eurecab** [WyriHaximus/react-guzzle-psr7#24]
Hello,

Since a few days I'm getting the error :
`Class 'React\HttpClient\Factory' not found`

From what I see, the method setHttpClient with null httpClient try to get an HttpClient from the missing class Factory. Which was replaced in a recent version.

We can still inject the http client to fix the problem but I think it would be nice to make the change on the README snippet.

**Comment by WyriHaximus** [comment]
Odd, I've changed some things in an underlying package. Will have a look when I get home tonight 👍

**Comment by WyriHaximus** [comment]
Filed #25 to solve this issue, thanks for reporting :+1:

**Comment by WyriHaximus** [comment]
`2.0.1` has been tagged with the fix from #25
