### ISSUE TITLE
Support for Guzzle request option 'http_errors'.

### ISSUE THREAD

**Issue by bartvanhoutte** [WyriHaximus/react-guzzle-psr7#28]
The Guzzle request option 'http_errors' is described in the [Guzzle documentation](http://docs.guzzlephp.org/en/stable/request-options.html#http-errors) as follows:

> Set to false to disable throwing exceptions on an HTTP protocol errors (i.e., 4xx and 5xx responses). Exceptions are thrown by default when HTTP protocol errors are encountered.

The HttpClientAdapter does not take this option into account, rejecting the promise even if http_errors was set to false.

See [patch.txt](https://github.com/WyriHaximus/react-guzzle-psr7/files/1737549/patch.txt) for a possible solution.

**Comment by WyriHaximus** [comment]
Sorry it took a bit, #32 is up with this suggestion. Thank you :+1:

**Comment by WyriHaximus** [comment]
Just released [`2.1.0`](https://github.com/WyriHaximus/react-guzzle-psr7/releases/tag/2.1.0) with this in it. Thanks!
