### ISSUE TITLE
asynchronous requests not working

### ISSUE THREAD

**Issue by akwatra** [WyriHaximus/react-guzzle-psr7#29]
Hi,

I tried with loop example: with send mail, 
this process like sync as not sent mail in behind. 

$loop = \React\EventLoop\Factory::create();
$handler = new \WyriHaximus\React\GuzzlePsr7\HttpClientAdapter($loop);

$client = new \GuzzleHttp\Client([
    'handler' => \GuzzleHttp\HandlerStack::create($handler),
]);

$client->getAsync('http://github.com/')->then(function ($response) {
    var_export($response);
    var_export((string) $response->getBody());
});

$client->getAsync('http://php.net/')->then(function ($response) {
    var_export($response);
    var_export((string) $response->getBody());
});

$loop->run();

**Comment by WyriHaximus** [comment]
Hey @akwatra, not sure where you are sending out the email, by the looks af that code you're just making HTTP calls.

**Comment by akwatra** [comment]
Hi, 
This was just example. 

i am calling **mailer-script ur**l with http call, and i do not want this to wait for a response from that url, just hit the url and let it work in background no wait for response

$client->getAsync('my-mail-script-url')->then(function ($response) {
var_export($response);
var_export((string) $response->getBody());
});


what i want: 
got post body
pass request params to mailscript | here want to asyn call so further process not wait 
and db check
and result to a user - will be receiving mail in few minutes.

**Comment by WyriHaximus** [comment]
Right so this adapter only makes making the call within your running event loop async. The event loop will keep running until it has nothing more to do. What you could do it use a message broker like rabbitmq or utilize redis as a message queue. And then use a cronjob or an always running script in the back ground to pick that message up and send the email. Personally I'm using https://github.com/jakubkulhan/bunny/ a lot

**Comment by WyriHaximus** [comment]
Release in [`2.0.2`](https://github.com/WyriHaximus/react-guzzle-psr7/releases/tag/2.0.2)
