### ISSUE TITLE
Impossible to pass certificate and private key to connector

### ISSUE THREAD

**Issue by TaelmanTim** [WyriHaximus/react-guzzle-psr7#49]
As mentioned in #4 the HttpClientAdapter doesn't accept options when a new adapter is created. Is there a possible fix for this?

**Comment by WyriHaximus** [comment]
Feel free to create a PR adding that feature, @clue already suggested a way of doing that here: https://github.com/reactphp/http-client/issues/140#issuecomment-507631269

**Comment by TaelmanTim** [comment]
👌
