### ISSUE TITLE
Adapter doesn't seem to work with CommandPool

### ISSUE THREAD

**Issue by JoelFeiner** [WyriHaximus/react-guzzle-psr7#50]
I'm using CommandPool to do batch downloading of files via S3. I believe I've set up the adapter correctly. I then wait on the promise using the guide here: https://github.com/WyriHaximus/react-guzzle-psr7/wiki/Promise-wait-alternatives. However, there is no sign that downloading is happening at all. Based on a timer also in my loop, I can see that the ReactPHP loop is running.

Code:
```
$LOOP = EventLoop\Factory::create();
$s3Client = new S3Client([
    'region'      => 'us-east-1',
    'version'     => '2006-03-01',
    'credentials' => [
        'key'    => 'KEY',
        'secret' => 'SECRET'
    ],
    'http_handler' => HandlerStack::create(new HttpClientAdapter($LOOP))
]);

$commands = function() use ($s3Client) {
    $key = 'key'; $bucket = 'some-bucket'; $remotePath = 'a/b/c'; $localPath = '/tmp/c';
    yield $key => $s3Client->getCommand('GetObject', [
            'Bucket' => $bucket,
            'Key'    => $remotePath
            'SaveAs' => $localPath
        ]);
};

$POOL = new CommandPool($s3Client, $commands(), [
    'concurrency' => 5,
    'before'      => function(CommandInterface $command, $key) {
        print "About to download file: $key\n";
        \gc_collect_cycles();
    },
    'fulfilled' => function(ResultInterface $result, $key, PromiseInterface $aggregatePromise) {
        print "Downloaded file: $key\n";
    },
    'rejected' => function(AwsException $ex, $key, PromiseInterface $aggregatePromise) {
        print "Failed to download file: $key: $ex\n";
    }
]);

$TIMER = $LOOP->addPeriodicTimer(1.0, function() {
    print "TIMER\n";
});

await(resolve($POOL->promise()), $LOOP);
```

All I see is "About to download file: ..." and then "TIMER" repeatedly. The files never download and no network traffic is generated.

I feel like I am missing something, but I'm not sure what. Is this even still supported?

**Comment by WyriHaximus** [comment]
That's interesting, it's been a while since I've used Guzzle so I can't vouch for how it's internals or the CommandPool deal with this tbh. You could try hooking into the progress options of Guzzle to see what happens: http://docs.guzzlephp.org/en/stable/request-options.html#progress

**Comment by JoelFeiner** [comment]
I ended up going a different route, so while this would be generally useful for the world, it's not urgent for me. Should I return to the issue, I'll try the suggestion and see if it gets me anywhere. I also don't know much about Guzzle internals.
